steps:
  # build the container image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/test-case-builder/test-case-builder", "."]
    # push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/test-case-builder/test-case-builder"]
    # Deploy container image to Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "beta",
        "run",
        "deploy",
        "--allow-unauthenticated",
        "test-case-builder",
        "--image",
        "gcr.io/test-case-builder/test-case-builder",
        "--region",
        "us-central1",
        "--platform",
        "managed",
        "--memory",
        "128Mi"
      ]
images:
  - gcr.io/test-case-builder/test-case-builder