version: "3"
services:
  kode:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PORT: 80
    image: koreview:1.1
    ports:
      - 8080:80
    volumes:
      - .:/var/www/html
    links:
      - pg
    depends_on:
      - pg
    environment:
      DATABASE_URL: postgres://postgres:docker@172.28.1.2/kode
      OAUTHAPP_GITHUB_CLIENT_ID: c84ea58cdbbd452632fb
      OAUTHAPP_GITHUB_CLIENT_SECRET: 88b309426f720fc6da6d28842d844941b745daf6
      OAUTHAPP_GITHUB_REDIRECT_URI: http://kode.konnector.local/oauth-github/auth
      DEBUG: 'true'
      SECURITY_SALT: 49e558df8e733a6daedbe054a9ccd7add9d9a6efa8a96cf3248815c364b47391
    networks:
      testing_net:
        ipv4_address: 172.28.1.1

  pg:
    image: postgres:latest
    ports:
    - 5432:5432
    volumes:
      - db_data:/var/lib/postgres
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: kode
    networks:
      testing_net:
        ipv4_address: 172.28.1.2
volumes:
  db_data: {}
networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
